config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get '/help', to: 'static_pages#help'

  get '/about', to: 'static_pages#about'

  get '/contact', to: 'static_pages#contact'

  get '/signup', to: 'users#new'

  # you can delete or comment it (if you wanna save for the future sake..)
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'

  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'

  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	attr_accessor :remember_token
	before_save { self.email = email.downcase }

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	validates :name, presence: true, length: { maximum: 50 }
	validates :email, presence: true, length: { maximum: 254 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
	validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

	has_secure_password

	class << self
		def digest(string)
			cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost

			BCrypt::Password.create(string, cost: cost)
		end

		def new_token
			SecureRandom.urlsafe_base64
		end
	end

	def remember
		self.remember_token = User.new_token
		update_attribute(:remember_digest, User.digest(remember_token))
	end

	def authenticated?(remember_token)
		return false if remember_digest.nil?
		BCrypt::Password.new(remember_digest).is_password?(remember_token)
	end

	def forget
		update_attribute(:remember_digest, nil)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)

  	if user && user.authenticate(params[:session][:password])
  		log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
  		redirect_back_or user
  	else
  		flash.now[:danger] = 'Invalid email/password combination'
  		render :new
  	end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: [:destroy]

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
  	@user = User.find(params[:id])
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)

  	if @user.save
      log_in @user
  		flash[:success] = "Welcome to the Sample App"
  		redirect_to @user
  	else
  		render :new
  	end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      flash[:success] = "Your profile updated"
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed complete"
    redirect_to users_url
  end

  private

  def user_params
  	params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "You have to login first to do what you wanna do.."
      redirect_to login_url
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to root_url unless current_user?(@user)
  end

  def admin_user
    redirect_to root_url unless current_user.admin?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = 'Sample App for Rails 5'

    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user_id] = user.id
	end

	def remember(user)
		user.remember
		cookies.permanent.signed[:user_id] = user.id
		cookies.permanent[:remember_token] = user.remember_token
	end

	def current_user?(user)
		user == current_user
	end

	def current_user
		if (user_id = session[:user_id])
			@current_user ||= User.find_by(id: session[:user_id])
		elsif (user_id = cookies.signed[:user_id])
			user = User.find_by(id: user_id)

			if user && user.authenticated?(cookies[:remember_token])
				log_in user
				@current_user = user
			end
		end
	end

	def logged_in?
		!current_user.nil?
	end

	def forget(user)
		user.forget
		cookies.delete(:user_id)
		cookies.delete(:remember_token)
	end

	def log_out
		forget(current_user)
		session.delete(:user_id)
		@current_user = nil
	end

	def redirect_back_or(default)
		redirect_to(session[:forwarding_url] || default)
		session.delete(:forwarding_url)
	end

	def store_location
		session[:forwarding_url] = request.original_url if request.get?
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user, options = {size: 80})
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
end

app/views/file_partials/_footer.html.erb
<footer class="footer">
	<nav>
		<ul>
			<li><%= link_to 'About', about_path %></li>
			<li><%= link_to 'Contact', contact_path %></li>
			<li><%= link_to 'News', 'http://news.railstutorial.org/' %></li>
		</ul>
	</nav>
</footer>

app/views/file_partials/_form.html.erb
<%= form_for @user do |f| %>
	<%= render "shared/error_messages" %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.label :email %>
	<%= f.email_field :email %>
	<%= f.label :password %>
	<%= f.password_field :password %>
	<%= f.label :passeord_confirmation, "Confirmation Password" %>
	<%= f.password_field :password %>
	<%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/file_partials/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<%= link_to 'sample_app', root_path, id: "logo" %>
		<nav>
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to 'Home', root_path %></li>
				<li><%= link_to 'Help', help_path %></li>
				<% if logged_in? %>
				<li><%= link_to "Users", users_path %></li>
				<li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li><%= link_to 'Profile', current_user %></li>
							<li><%= link_to 'Settings', edit_user_path(current_user) %></li>
							<li class="divider"></li>
							<li><%= link_to 'Log Out', logout_path, method: :delete %></li>
						</ul>
					</li>
				<% else %>
				<li><%= link_to 'Login', login_path %></li>
				<% end %>
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<%= render 'file_partials/header' %>
	<div class="container">
    <%= render 'shared/flash_messages' %>
		<%= yield %>
		<%= render 'file_partials/footer' %>
	 <%= debug(params) if Rails.env.development? %>
  </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-danger">
			The form contains <%= pluralize(@user.errors.count, "error") %>:
		</div>
		<ul>
		<% @user.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About")%>
<h1>About</h1>
<p>
  Fap echo park you probably haven't heard of them, salvia raw denim hella kickstarter 90's slow-carb forage post-ironic. Keffiyeh kitsch ethical, tacos tattooed celiac green juice selfies. Letterpress skateboard normcore art party. Polaroid flexitarian freegan, aesthetic PBR&B organic pabst cronut. Cornhole tacos selfies aesthetic mixtape, umami beard pop-up swag pinterest. Mixtape keffiyeh listicle austin, meh portland typewriter kombucha biodiesel blue bottle hammock fixie cray tumblr pabst. Bicycle rights health goth pinterest blog whatever farm-to-table trust fund, food truck shoreditch.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact")%>
<h1>Contact</h1>
<p>
  Fap leggings scenester ethical. Ethical tattooed tousled 8-bit. Shoreditch dreamcatcher yuccie, celiac tumblr drinking vinegar viral mustache farm-to-table letterpress. You probably haven't heard of them authentic brooklyn, 3 wolf moon echo park etsy vice fashion axe leggings pabst asymmetrical fanny pack man bun affogato scenester. Selfies wolf selvage, truffaut fap marfa butcher lumbersexual brooklyn cold-pressed. Chillwave cardigan street art truffaut, distillery try-hard leggings. Chia mumblecore franzen, iPhone quinoa brunch art party sriracha.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help")%>
<h1>Help</h1>
<p>
  Fanny pack cold-pressed yr cred. Kombucha bitters franzen, dreamcatcher deep v chartreuse banjo poutine intelligentsia pinterest. Lomo iPhone aesthetic, tousled messenger bag 90's pinterest biodiesel swag jean shorts irony everyday carry. Jean shorts typewriter next level offal meggings, narwhal lo-fi cray freegan leggings schlitz. Kinfolk celiac fingerstache synth aesthetic. Pickled ennui post-ironic, PBR&B offal schlitz shabby chic. Paleo squid scenester you probably haven't heard of them vegan hashtag direct trade actually fashion axe tofu.
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
	<h1>Home!</h1>
	<p>
	  Banh mi beard tattooed fingerstache jean shorts cornhole cardigan, pug affogato shoreditch pop-up waistcoat YOLO. Art party banjo mlkshk affogato stumptown farm-to-table kogi, post-ironic ennui crucifix tattooed heirloom trust fund taxidermy cray. Fap sustainable vegan, vinyl single-origin coffee chillwave four loko venmo meditation seitan mlkshk ennui health goth flannel hammock. Bitters bushwick distillery synth sartorial, cronut beard salvia fixie affogato church-key forage YOLO food truck next level. Gluten-free leggings photo booth yuccie truffaut. Disrupt authentic banjo, organic cold-pressed fashion axe cred hella pour-over. 8-bit selfies gentrify helvetica, schlitz bespoke crucifix health goth.
	</p>
	<%= link_to 'Sign up now!', signup_path, class: "btn btn-lg btn-primary" %>
</div>
<%= link_to image_tag('rails.png', alt: 'Rails Logo'), 'http://rubyonrails.org' %>

app/views/users/_user.html.erb
<li>
	<%= gravatar_for user, size: 50 %>
	<%= link_to user.name, user %>

	<% if current_user.admin? && !current_user?(user)%>
		| <%= link_to "delete", user, method: :delete, data: {confirm: "Are you want to delete #{user.name}? "} %>
	<% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit User") %>
<% provide(:button_text, "Save Changes") %>
<h1>Update Your Profile</h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= render 'file_partials/form' %>
		<div class="gravatar_edit">
			<%= gravatar_for @user %>
			<%= link_to 'change', 'http://gravatar.com/emails', target: "_blank" %>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All Users') %>
<h1>All Users</h1>
<%= will_paginate %>
<ul class="users">
	<%= render @users %>
</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, "Sign up")%>
<% provide(:button_text, "Create my account") %>
<h1>Sign up</h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= render 'file_partials/form' %>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
	<aside class="col-md-4">
		<section class="user_info">
			<h1>
				<%= gravatar_for @user %>
				<%= @user.name %>
			</h1>
		</section>
	</aside>
</div>